# These are supported funding model platforms

patreon: pengubot
open_collective: # Replace with a single Open Collective username
ko_fi: adityatd
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
